# Generated by Django 4.1.7 on 2023-03-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="event_photos/")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("distance", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pace", models.TimeField()),
                ("overall_position", models.IntegerField()),
                ("age_position", models.IntegerField()),
                ("age_category", models.CharField(max_length=10)),
                ("certificate", models.FileField(upload_to="certificates/")),
                ("photos", models.ManyToManyField(blank=True, to="events.photo")),
            ],
        ),
    ]
