# Generated by Django 4.1.7 on 2023-04-01 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.ImageField(upload_to="assets/")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("distance", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pace", models.TimeField()),
                ("overall_position", models.IntegerField()),
                ("age_position", models.IntegerField()),
                ("age_category", models.CharField(max_length=10)),
                (
                    "certificate",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate",
                        to="events.asset",
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True, related_name="photos", to="events.asset"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
