# Generated by Django 4.1.7 on 2023-04-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_asset_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="distance",
            field=models.IntegerField(),
        ),
    ]
