# Generated by Django 4.1.7 on 2023-04-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="certificate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificate",
                to="events.asset",
            ),
        ),
    ]
